spring:
  application:
    name: cis-user-management-api
  datasource:
    url: jdbc:mysql://localhost:3306/sd3?useSSL=false&serverTimezone=UTC
    username: root
    password: sd5   # Change in production / use secrets
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none   # Important! Do not touch schema (R3)
    show-sql: true     # Useful in dev
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 8080

logging:
  level:
    org.springframework: INFO
    com.cis.api: DEBUG